### ISSUE TITLE
Incorrect status line rendering

### ISSUE THREAD

**Issue by lcrockett** [sheoak/neomutt-powerline-nerdfonts#5]
# Description

It looks like the right side of the status line is not filled in properly. For instance, when opening an e-mail that contains an attachment, I would expect the background to be yellow, just like the example screenshot in the README.

For some reason it gets filled with the background color instead. Not sure if this is related to the Powerline theme or a terminal setting.

# Additional information
```
System: Darwin 19.3.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
GPGME: 1.13.1
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: tokyocabinet, lmdb

Configure options: --prefix=/usr/local/Cellar/neomutt/20200501 --enable-gpgme --with-gpgme=/usr/local/opt/gpgme --gss --lmdb --notmuch --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses --lua --with-lua=/usr/local/opt/lua

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/opt/gpgme/include -I/usr/local/opt/libassuan/include -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/neomutt/20200501/include -I/usr/local/opt/lua/include/lua5.3 -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn -inotify
  -locales_hack +lua -lz4 +meta -mixmaster +nls +notmuch +openssl +pgp +regex
  +sasl +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20200501/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20200501/etc"
```

# Screenshots

![neomutt-powerline-00](https://user-images.githubusercontent.com/58056722/81130813-64845480-8f49-11ea-998a-4141994fffd7.png)

![neomutt-powerline-01](https://user-images.githubusercontent.com/58056722/81130816-664e1800-8f49-11ea-91df-aa15bb93266e.png)

**Comment by sheoak** [comment]
As mentionned, this configuration is a bit of a hack because of missing features in neomutt. I have to check recent updates to see if I can get something more stable. For now it really depends on how your terminal colors are configured. Can you try in a different terminal?

**Comment by lcrockett** [comment]
I've tried a few other terminals, besides iTerm, the MacOs built-in `terminal` application shows the same results. If you have any updates in the future of what I could be trying out, that would be greatly appreciated. Cheers !

**Comment by sheoak** [comment]
I remember playing around with colors from .Xdefaults.
Does it always happen when you open an attachment, or just sometimes?

**Comment by lcrockett** [comment]
It always happens. However, i've since changed the layout of the status bar as such that this doesn't come up anymore. Cheers !

**Comment by PhrantiK** [comment]
For posterity's sake, macos apparently doesn't recognise PCRE extensions like \s and \b.

Replacing the \s with [[:space:]] works on macos:

```
# powerline status bar hack
color status green black ''
color status yellow black ''
color status red black ''
color status brightblack blue '(.*)' 1
color status blue black '.*()' 1
color status black blue '[[:space:]]* [0-9]+[[:space:]]*'
color status blue black '().*$' 1
color status yellow black '()[[:space:]]*[[:space:]]*[0-9]+[[:space:]]*' 1
color status black yellow '[[:space:]]*[[:space:]]*[0-9]+[[:space:]]*'
color status blue yellow '() ([0-9]+%|all|end) [[:space:]]*' 1
color status black blue ' ([0-9]+%|all|end) [[:space:]]*'
color status yellow black '()[[:space:]]*' 1
color status default black ''
```

**Comment by sheoak** [comment]
Thanks @PhrantiK I will try to have a look and update it when I have some free time
