### ISSUE TITLE
New neomutt version breaks attach_format

### ISSUE THREAD

**Issue by mlmatlock** [sheoak/neomutt-powerline-nerdfonts#8]
Arch, fully up to date.

Neomutt version: NeoMutt 20240323-22-ca6645-dirty

Error message: /home/merell/.config/neomutt/powerline:11: Option attach_format: Unknown expando: %
/home/merell/.config/neomutt/neomuttrc:9: source: file /home/merell/.config/neomutt/powerline could not be sourced
source: errors in /home/merell/.config/neomutt/neomuttrc

Config line: set attach_format = "%u%D  %T%-75.75d %?T?%&   ? %5s · %m/%M"

Ideas, other than commenting line out?

**Comment by mricon** [comment]
It's the "%&" in the line -- that "%" needs to be removed. This is the fixed version:
```set attach_format = "%u%D  %T%-75.75d %?T?&   ? %5s · %m/%M"```

**Comment by mlmatlock** [comment]
@mricon, that did the trick, thanks!
